Smoke Test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -364,6 +364,63 @@ jobs:
 
       - destroy-environment
 
+  smoke-test:
+    docker:
+      - image: alpine:latest 
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache aws-cli curl tar gzip nodejs npm
+
+      - run:
+          name: print inventory.txt from workspace
+          command: |
+            cat ~/inventory.txt
+      
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --region us-east-1 \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            curl -s "${API_URL}/api/status" -v
+
+            if curl -s "${API_URL}/api/status" -v  | grep "ok"
+            then
+                 
+              echo "backend smoketest succeed"
+              exit 0
+              
+            else
+              echo "Backend smoke test failed. check the issue"
+              exit 1
+            fi
+
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              echo "frontend smoke test success"
+              exit 1
+            else
+              echo "frontend smoke test failed"
+              exit 1
+            fi
+
+      - destroy-environment
+
 workflows:
   default:
     jobs:
